# Markdownlint configuration.

# For more information, see: https://github.com/DavidAnson/markdownlint#optionsconfig.

# Enable all rules.
default: true

# NOTE: The line-length rule is currently not strict enough.
# For more details, see: https://github.com/DavidAnson/markdownlint/issues/237.
line-length:
  # Allow longer lines for code blocks since account ids are 64 characters long
  # by themselves.
  code_block_line_length: 400

no-inline-html:
  allowed_elements:
    # Allow raw <code> ... </code> elements because we use it as a work-around
    # for lack of Vuepress' support for inline double curly braces that we use
    # for denoting variables.
    # For more details, see: https://github.com/vuejs/vuepress/issues/853.
    - code

# Do not always require language specifiers with fenced code blocks since they
# are not part of the Markdown spec.
fenced-code-language: false
