dictionaries:
  - en
  - en_GB

excluded_files:
  - "build-scripts/**/*"
  - "Src/**/*"
  - "Tools/**/*"
  - ".typo-ci.yml"
  - ".astylerc"
  - ".flake8"
  - ".gitignore"
  - "cmake_uninstall.cmake.in"
  - "CMakeLists.txt"
  - "json_blacklist"
  - "LICENSE"
  - "Makefile"
  - "style-json.ps1"

excluded_words:
  - cdda
  - dda
  - cata
  - Zets
  - overmap
  - Magiclysm
  - uncraft
  - Nocts
  - tefnut
  - evac
  - cyberjunkie
  - medikit
  - triffgus
  - wildy
  - D'ya
  - bfg
  - omnicam
  - attunements
  - technomancer
  - factionless
  - npc
  - npcs
  - tshirt
  - bommers
  - veh
  - Dinomod
  - Nechronica
  - IchBinNexus
  - PoraComp
  - Pharm
  - Porawep
  - Touhou
  - jrr
  - eyebot
  - orjson
  - shutil
  - reformatter
  - bads
  - FictonalWeapons
  - fic
  - ficmags
  - necronimicron
  - cbm
  - cbms
  - thegoatgodgit
  - GreiCars
  - astyle
  - sunesthesia
  - afs
  - stim
  - sungel
  - vitA
  - vitB
  - vitC
  - jihelucake
  - Garand
  - Berettas
  - Benilli
  - FOODCO's
  - jabberwock
  - Xotto
  - expan
  - boxs
  - Jordans
  - Rais
  - Choco
  - Krave
  - Wkk
  - Nesquik
  - Oatie
  - Weetabix
  - Oatibix
  - Alpen
  - Frusli
  - Frosties
  - Mcvitie
  - Lizis
  - Chia
  - Moma
  - Oomf
  - Superseeded
  - spezi
  - fchicken
  - nachosc
  - nachosm
  - toastem
  - toasterpastryfrozen
  - sloppyjoe
  - grahmcrackers
  - lutefisk
  - kompot
  - chilidogs
  - crispycran
  - dayquil
  - ecig
  - foon
  - halligan
  - mbag
  - slingpack
  - neccowafers
  - picklocks
  - quikclot
  - teleumbrella
  - vacutainer
  - veggy
  - xacto
  - xanax
  - ssWWWWWWWWssssssssssssss
  - tttt
  - ttttt
  - rrr
  - brandcerealmod
  - KantoJolto
  - Kelloggs
  - Mollys
  - colamdew
  - nachosmc
  - tazer
  - chems
  - windowspowershell
  - Abrahms
  - Kawaii
  - Whaleys
  - Touyou
  - xtal
  - Nimian
  - Axema
  - Kenan
  - Uekibati
  - Shosyoji
  - Umeboshi
  - Eirenex
  - toram
  - cheongsam's
  - mxocosmetics
