on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

name: Release new version
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vweevers/additional-tags-action@v1
