name: .json bug check

on:
  push:
    path:
    - '**.json'
  pull_request:
    paths:
    - '**.json'

jobs:
  style-json:
    name: JSON style check

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 10
      - name: install astyle
        run: sudo apt-get install -y astyle
      - name: JSON style check
        run: make style-json
      - name: Commit files
        if: failure()
        run: |
          git config --local user.email "TheGoatGod@users.noreply.github.com"
          git config --local user.name "Json linter"
          git add -A
          git commit -m '.json linted'
          cd Community-Mod-Compilation-redux
          git push -u origin
      - name: Display Corrections
        if: failure()
        run: git diff
