name: .json bug check

on:
  push:
    path:
    - '**.json'
  pull_request:
    paths:
    - '**.json'

jobs:
  style-json:
    name: JSON style check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 10
      - name: install astyle
        run: sudo apt-get install -y astyle
      - name: JSON style check
        run: make style-json
      - name: Commit files
        if: failure()
        env:
          CI_USER: TheGoatGod
          CI_EMAIL: "TheGoatGod@users.noreply.github.com"
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"
          git commit -m '[workflow] .json linted' && echo "push=true" >> $GITHUB_ENV
      - name: Display Corrections
        if: failure()
        run: git diff
      - name: Push changes
        if: failure() || env.push == 'true'
        env:
          CI_USER: TheGoatGod
          CI_TOKEN: ${{ secrets.WORKFLOW }}
        run: |
          git push -u "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" origin current
