name: .json bug check

on:
  push:
    path:
    - '**.json'
  pull_request:
    paths:
    - '**.json'

jobs:
  style-json:
    name: JSON style check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 10
      - name: install astyle
        run: sudo apt-get install -y astyle
      - name: JSON style check
        run: make style-json
      - name: Display Corrections
        if: failure()
        run: git diff
      - name: Push changes
        if: failure()
        env:
          CI_USER: TheGoatGod
          CI_TOKEN: ${{ secrets.WORKFLOW }}
          push: true
        run: |
          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master
