on:
  pull_request:
    paths:
    - '**.py'

name: Style check - Python
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - name: Install dependencies
      run: sudo apt-get install flake8 | sudo apt-get install -y astyle
    - name: Enable flake8 problem matcher
      run: echo "::add-matcher::build-scripts/problem-matchers/flake8.json"
    - name: Run Flake8
      run: make python-check
