on:
  pull_request:
    paths:
    - '**.json'

name: Style check - JSON
jobs:
  style-json:
    name: Style check - JSON

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 10
      - name: Install dependencies
        run: sudo apt-get install -y astyle
      - name: Style check - JSON
        run: make style-json
      - name: Display Corrections
        if: failure()
        run: git diff
